User.create(username: "MikeSpeed", email: "mikespeed@gmail.com", password: "Kazakhstan2017")
User.create(username: "Zforce", email: "z@flatiron.com", password: "Kidsontheblock")
User.create(username: "MattyHatsandGloves", email: "risktaker@yahoo.com", password: "Rinaldigroup")
User.create(username: "MommaSchiumo", email: "momma@schiumo.com", password: "CasaSchiuma")
User.create(username: "Kamil", email: "polak03@art.com", password: "RowanMed")

Exercise.create(name: "Bicep Curl", muscle_group: "Arms", user_id: 1 )
Exercise.create(name: "Bench Press", muscle_group: "Chest", user_id: 2)
Exercise.create(name: "Lat Pulldown", muscle_group: "Back", user_id: 3)
Exercise.create(name: "Squats", muscle_group: "Legs", user_id: 4)
Exercise.create(name: "Cardio", muscle_group: "N/A", user_id: 5)
